---
version: '2'

services:

  blockchain-explorer:
    container_name: blockchain-explorer
    image: cdmhack/blockchain-explorer
    restart: always
    ports:
      - "3333:3333"
      - "8080:8089"
    network_mode: bridge
    hostname: blockchain-explorer
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=fabricexplorer
      - DATABASE_USERNAME=pguser
      - DATABASE_PASSWD=pgpass 

